In [22]:
import pandas as pd

In [23]:
df = pd.read_csv("../data/train.csv")

In [24]:
df

,qid,scenario,question,ground_truth,student_incorrect_solution,student_profile,teacher_described_confusion,self-correctness,self-typical-confusion,self-typical-interactions,conversation
0,5000012,1,Nancy is filling an aquarium for her fish. She...,First calculate the volume of the aquarium by ...,The aquarium has a volume of 4 x 6 x 3 = 72 cu...,Steven is a 7th grade student. He has difficul...,He added a step after completing the problem.,Yes,3.0,3.0,"Teacher: (probing)Steven, If you had 4 of some..."
1,5000084,2,John is very unfit and decides to work up to d...,He needs to do 15*3=45 progressions\nThat will...,"To get to 15 reps, John will take 15 - 1 = 14 ...",Stephanie is a 7th grade student. She has diff...,She became fixated on a wrong calculation and ...,No,2.0,2.0,"Teacher: (probing)Stephanie, How many days wil..."
2,5000982,3,James has 20 pairs of red socks and half as ma...,He has 20/2=10 black socks\nSo he has 20+10=30...,James has 20/2 = 10 pairs of black socks.\nJam...,DeAndre is a 7th grade student. He has problem...,He was technically correct.,Yes,5.0,5.0,"Teacher: (probing)DeAndre, you successfully an..."
3,5000274,4,Jason drives past 3 convenience stores on his ...,First find the additional distance between the...,The distance between the second store and thir...,Winnie is a 7th grade student. She struggle to...,He understood it when it was broken down step ...,Yes,3.0,3.0,Teacher: (probing)What is the distance between...
4,5000797,5,Wanda walks her daughter .5 miles to school in...,She walks .5 miles to school and back 4 times ...,"Every day, Wanda walks a total of 0.5 + 0.5 = ...",Cody is a 7th grade student. He has problem wi...,He forgot she walked twice each day!,Yes,3.0,3.0,"Teacher: (probing)Cody, How far doe Wanda walk..."
...,...,...,...,...,...,...,...,...,...,...,...
2257,5000895,4,Greta worked 40 hours and was paid $12 per hou...,"For the 40 hours worked, Greta earned a total ...",Greta earned 40 x $12 = $480 for 40 hours of w...,Mariana is a 7th grade student. She struggle t...,They just needed to divide $480 by $15 per hour,Yes,3.0,3.0,Teacher: (generic)Hi Mariana can you explain y...
2258,5000596,5,"In four years, Suzy will be twice Mary's age t...","In four years, Suzy will be 20+4=24.\nThen Mar...",Let's start by finding out how old Suzy will b...,Winnie is a 7th grade student. She has problem...,They needed to work out how old she is now,Yes,3.0,3.0,Teacher: (generic)Hi Winnie can you explain yo...
2259,5000862,1,James supercharges his car which increases his...,He increased his speed by 150*.3=45 mph\nSo hi...,"First, we need to find out how much the superc...",Riya is a 7th grade student. She struggle most...,had confused the 15% weight decrease with a 15...,Yes,5.0,5.0,"Teacher: (generic)Morning Riya, can you talk m..."
2260,5000171,2,James turned 23 the same time John turned 35. ...,James is 35-23=12 years younger than John\n5 y...,The difference in age between James and John i...,Mariana is a 7th grade student. She has proble...,the student had subtracted 5 instead of adding 5,Yes,5.0,5.0,"Teacher: (generic)Morning Mariana, can you tal..."
2261,5000143,3,Two vampires have come to the sleepy village o...,First find the number of new vampires after on...,"After the first night, each vampire will have ...",Lakisha is a 7th grade student. She has proble...,they seemed to findamentally misunderstand wha...,Yes,2.0,2.0,"Teacher: (generic)Morning Lakisha, can you tal..."

In [28]:
question_answer_pairs = []

for index, row in df.iterrows():
    question_answer_pairs.append({
        'id': len(question_answer_pairs), 
        'question': row['question'], 
        'answer': row['ground_truth']
    })

In [30]:
import json
with open("../data/qestion_answer_pairs.json", "w") as jsonFile:
    json.dump(question_answer_pairs, jsonFile, indent=4)